### ISSUE TITLE
convert-video missing

### ISSUE THREAD

**Issue by luisdralves** [rccavalcanti/KDE-ServiceMenus#4]
Hello, 
It seems that both service menus for converting video (dirToMp4 and convertVideo) are using a custom script, `convert-video`. I'd appreciate it if you could add it to the git repo.

**Comment by rc2dev** [comment]
Hi,

`convert-video` is tracked [in this other repo](https://github.com/rccavalcanti/scripts/blob/master/general/convert-video).
Place it in your PATH, make it executable and you are good to go. Also be sure to have `ffmpeg` installed.

**Comment by luisdralves** [comment]
Thank you for your work
